use hr;
CREATE TABLE `EMPLOYEE` (
	`EMPLOYEE_PK_ID`	VARCHAR(30)	NOT NULL,
	`MEMBER`	VARCHAR(20)	NULL,
	`DEPT_FK_ID`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `EMPLOYEE_ATTENDANCE` (
	`WORK_ATT_PK_ID`	VARCHAR(20)	NOT NULL,
	`EMPLOYEE_FK_ID`	VARCHAR(20)	NOT NULL,
	`WORK_STAT_FK_ID`	VARCHAR(20)	NOT NULL,
	`DATE`	VARCHAR(20)	NULL
);

CREATE TABLE `DEPT` (
	`DEPT_PK_ID`	VARCHAR(20)	NOT NULL,
	`DEPT_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `WORK_STATUS` (
	`WORK_STAT_PK_ID`	VARCHAR(20)	NOT NULL,
	`STATUS`	VARCHAR(20)	NULL
);

CREATE TABLE `AUTH_NAMES` (
	`UNIQUE_ID`	VARCHAR(20)	NOT NULL,
	`AUTH_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `AUTHS` (
	`UNIQUE_ID`	VARCHAR(20)	NOT NULL,
	`EMPLOYEE_FK_ID`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `EMPLOYEE` ADD CONSTRAINT `PK_EMPLOYEE` PRIMARY KEY (
	`EMPLOYEE_PK_ID`
);

ALTER TABLE `EMPLOYEE_ATTENDANCE` ADD CONSTRAINT `PK_EMPLOYEE_ATTENDANCE` PRIMARY KEY (
	`WORK_ATT_PK_ID`,
	`EMPLOYEE_FK_ID`,
	`WORK_STAT_FK_ID`
);

ALTER TABLE `DEPT` ADD CONSTRAINT `PK_DEPT` PRIMARY KEY (
	`DEPT_PK_ID`
);

ALTER TABLE `WORK_STATUS` ADD CONSTRAINT `PK_WORK_STATUS` PRIMARY KEY (
	`WORK_STAT_PK_ID`
);

ALTER TABLE `AUTH_NAMES` ADD CONSTRAINT `PK_AUTH_NAMES` PRIMARY KEY (
	`UNIQUE_ID`
);

ALTER TABLE `AUTHS` ADD CONSTRAINT `PK_AUTHS` PRIMARY KEY (
	`UNIQUE_ID`,
	`EMPLOYEE_FK_ID`
);

ALTER TABLE `EMPLOYEE_ATTENDANCE` ADD CONSTRAINT `FK_EMPLOYEE_TO_EMPLOYEE_ATTENDANCE_1` FOREIGN KEY (
	`EMPLOYEE_FK_ID`
)
REFERENCES `EMPLOYEE` (
	`EMPLOYEE_PK_ID`
);

ALTER TABLE `EMPLOYEE_ATTENDANCE` ADD CONSTRAINT `FK_WORK_STATUS_TO_EMPLOYEE_ATTENDANCE_1` FOREIGN KEY (
	`WORK_STAT_FK_ID`
)
REFERENCES `WORK_STATUS` (
	`WORK_STAT_PK_ID`
);

ALTER TABLE `AUTHS` ADD CONSTRAINT `FK_AUTH_NAMES_TO_AUTHS_1` FOREIGN KEY (
	`UNIQUE_ID`
)
REFERENCES `AUTH_NAMES` (
	`UNIQUE_ID`
);

ALTER TABLE `AUTHS` ADD CONSTRAINT `FK_EMPLOYEE_TO_AUTHS_1` FOREIGN KEY (
	`EMPLOYEE_FK_ID`
)
REFERENCES `EMPLOYEE` (
	`EMPLOYEE_PK_ID`
);

